### ISSUE TITLE
Recipe doesnt work (spelling mistake)

### ISSUE THREAD

**Issue by FlionkJ** [TheMillman/OtherBlocks#1]
Hey you make an spelling mistake in the dirt stairs recipe. Can you correct it?
Greetings FlionkJ

[dirt_stairs.txt](https://github.com/TheMillman/OtherBlocks/files/6361612/dirt_stairs.txt)

**Comment by TheMillman** [comment]
Thanks for telling me about the dirt stairs recipe problem, I will solve the problem as soon as possible but until next week I can't because I don't have the computer with me.
This is the correct file replace it with the wrong one. Make sure the file is .json otherwise it won't work.

[dirt_stairs.txt](https://github.com/TheMillman/OtherBlocks/files/6361776/dirt_stairs.txt)
Change the file from .txt to .json

Thanks again and Greetings The_Millman

**Comment by TheMillman** [comment]
I fixed the problem in the latest update.
